### [CVE-2025-48432](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-48432)
![](https://img.shields.io/static/v1?label=Product&message=Django&color=blue)
![](https://img.shields.io/static/v1?label=Version&message=4.2%20&color=brightgreen)
![](https://img.shields.io/static/v1?label=Version&message=5.1%20&color=brightgreen)
![](https://img.shields.io/static/v1?label=Version&message=5.2%20&color=brightgreen)
![](https://img.shields.io/static/v1?label=Vulnerability&message=CWE-117%20Improper%20Output%20Neutralization%20for%20Logs&color=brightgreen)

### Description

An issue was discovered in Django 5.2 before 5.2.3, 5.1 before 5.1.11, and 4.2 before 4.2.23. Internal HTTP response logging does not escape request.path, which allows remote attackers to potentially manipulate log output via crafted URLs. This may lead to log injection or forgery when logs are viewed in terminals or processed by external systems.

### POC

#### Reference
No PoCs from references.

#### Github
- https://github.com/ARPSyndicate/cve-scores
- https://github.com/ch4n3-yoon/ch4n3-yoon
- https://github.com/graydonhope/VulnerabilityScanner
- https://github.com/thexnumb/thexwriteup
- https://github.com/w4zu/Debian_security

