### [CVE-2024-32879](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-32879)
![](https://img.shields.io/static/v1?label=Product&message=social-app-django&color=blue)
![](https://img.shields.io/static/v1?label=Version&message=%3D%20%3C%205.4.1%20&color=brighgreen)
![](https://img.shields.io/static/v1?label=Vulnerability&message=CWE-178%3A%20Improper%20Handling%20of%20Case%20Sensitivity&color=brighgreen)
![](https://img.shields.io/static/v1?label=Vulnerability&message=CWE-303%3A%20Incorrect%20Implementation%20of%20Authentication%20Algorithm&color=brighgreen)

### Description

Python Social Auth is a social authentication/registration mechanism. Prior to version 5.4.1, due to default case-insensitive collation in MySQL or MariaDB databases, third-party authentication user IDs are not case-sensitive and could cause different IDs to match. This issue has been addressed by a fix released in version 5.4.1. An immediate workaround would be to change collation of the affected field.

### POC

#### Reference
No PoCs from references.

#### Github
- https://github.com/fkie-cad/nvd-json-data-feeds

