### [CVE-2012-2135](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-2135)
![](https://img.shields.io/static/v1?label=Product&message=n%2Fa&color=blue)
![](https://img.shields.io/static/v1?label=Version&message=%3D%20n%2Fa%20&color=brighgreen)
![](https://img.shields.io/static/v1?label=Vulnerability&message=n%2Fa&color=brighgreen)

### Description

The utf-16 decoder in Python 3.1 through 3.3 does not update the aligned_end variable after calling the unicode_decode_call_errorhandler function, which allows remote attackers to obtain sensitive information (process memory) or cause a denial of service (memory corruption and crash) via unspecified vectors.

### POC

#### Reference
- http://www.ubuntu.com/usn/USN-1616-1

#### Github
No PoCs found on GitHub currently.

