### [CVE-2022-1289](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-1289)
![](https://img.shields.io/static/v1?label=Product&message=Furnace&color=blue)
![](https://img.shields.io/static/v1?label=Version&message=n%2Fa&color=blue)
![](https://img.shields.io/static/v1?label=Vulnerability&message=CWE-404%20Denial%20of%20Service&color=brighgreen)

### Description

A denial of service vulnerability was found in tildearrow Furnace. It has been classified as problematic. This is due to an incomplete fix of CVE-2022-1211. It is possible to initiate the attack remotely but it requires user interaction. The issue got fixed with the patch 0eb02422d5161767e9983bdaa5c429762d3477ce.

### POC

#### Reference
- https://github.com/tildearrow/furnace/issues/325#issuecomment-1094139655

#### Github
No PoCs found on GitHub currently.

